CREATE DATABASE IF NOT EXISTS XX_DB_NAME CHARACTER SET utf8 COLLATE utf8_bin;
--CREATE USER 'XX_DB_USERNAME';
--SET PASSWORD FOR 'XX_DB_USERNAME'@'%'=PASSWORD('XX_DB_USERPW');
GRANT ALL PRIVILEGES ON XX_DB_NAME.* TO 'XX_DB_USERNAME'@'%' identified by 'XX_DB_USERPW';
FLUSH PRIVILEGES;
USE XX_DB_NAME;