---    
    - name: Build de l'image logicaldoc
      docker_image:
        name: logicaldoc
        build:
          args:
          path: .
          dockerfile: Dockerfile
          state: present
          source: build
          nocache: true

    - name: lancement d'un conteneur logicaldoc
      docker_container:
        name: "{{ ldoc_container_name }}"
        image: logicaldoc:latest
        ports: "{{ port }}:8080"
        state: started
        tty: yes
        pull: no
        env:
          DB_ENGINE: "{{ sgbd }}"
          DB_NAME: logicaldoc
          DB_USERNAME: ldoc
          DB_USERPW: picon
          DB_HOST: "{{ db_host }}"
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_HOST: '%'
          POSTGRES_PASSWORD: root
        networks:
          - name: subnet1
