---
    - name: Installation de Python
      apt:
        name: "{{ item }}"
        state: present
        force: yes
      with_items:
        - python
        - python-py
        - python-pip
    - name: Installation de Docker
      apt:
        name: docker
        state: present
        force: yes
    - name: Installation d'Ansible (via pip)
      pip:
        name: ansible
        state: present
        force: yes
    - name: Installation d'Ansible (via apt)
      apt:
        name: ansible
        state: present
        force: yes